import Navbar from '@/components/nav-bar';
import { Box } from '@mui/material';
import TopBar from '@/components/top-bar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <TopBar></TopBar>
        <Box
          component="section"
          className="layout"
          sx={{ display: 'flex', py: 1, px: 0 }}
        >
          <Navbar />
          <Box component="main" sx={{ flexGrow: 1 }}>
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
