use("test")

// if specified, clear out all existing collections (except the users collection)
if (true) {
   db.donors.deleteMany({})
   db.users.deleteMany({})
   db.items.deleteMany({})
   db.donationItem.deleteMany({})
   db.donations.deleteMany({})
}

// create 10 donorID variables
for (let i = 1; i <= 10; i++) {
  this[`donorID${i}`] = ObjectId();
}

db.donors.insertMany([
    {
        "_id": donorID1,
        "lastName": "Smith",
        "firstName": "John",
        "email": "john.smith@example.com",
        "address": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345"
    },
    {
        "_id": donorID2,
        "lastName": "Johnson",
        "firstName": "Emily",
        "email": "emily.johnson@example.com",
        "address": "456 Elm St",
        "city": "Smallville",
        "state": "NY",
        "zip": "54321"
    },
    {
        "_id": donorID3,
        "lastName": "Williams",
        "firstName": "David",
        "email": "david.williams@example.com",
        "address": "789 Oak St",
        "city": "Metropolis",
        "state": "IL",
        "zip": "67890"
    },
    {
        "_id": donorID4,
        "lastName": "Brown",
        "firstName": "Sarah",
        "email": "sarah.brown@example.com",
        "address": "101 Pine St",
        "city": "Gotham",
        "state": "NJ",
        "zip": "13579"
    },
    {
        "_id": donorID5,
        "lastName": "Jones",
        "firstName": "Michael",
        "email": "michael.jones@example.com",
        "address": "246 Cedar St",
        "city": "Central City",
        "state": "MO",
        "zip": "24680"
    },
    {
        "_id": donorID6,
        "lastName": "Davis",
        "firstName": "Jessica",
        "email": "jessica.davis@example.com",
        "address": "369 Maple St",
        "city": "Star City",
        "state": "WA",
        "zip": "97531"
    },
    {
        "_id": donorID7,
        "lastName": "Wilson",
        "firstName": "Daniel",
        "email": "daniel.wilson@example.com",
        "address": "483 Birch St",
        "city": "Atlantis",
        "state": "CA",
        "zip": "12345"
    },
    {
        "_id": donorID8,
        "lastName": "Taylor",
        "firstName": "Amanda",
        "email": "amanda.taylor@example.com",
        "address": "579 Fir St",
        "city": "Themyscira",
        "state": "MA",
        "zip": "54321"
    },
    {
        "_id": donorID9,
        "lastName": "Martinez",
        "firstName": "Chris",
        "email": "chris.martinez@example.com",
        "address": "678 Pine St",
        "city": "Xavier's School for Gifted Youngsters",
        "state": "NY",
        "zip": "67890"
    },
    {
        "_id": donorID10,
        "lastName": "Garcia",
        "firstName": "Jennifer",
        "email": "jennifer.garcia@example.com",
        "address": "789 Elm St",
        "city": "Hogwarts",
        "state": "PA",
        "zip": "13579"
    },
])

// creates 10 userID variables
for (let i = 1; i <= 10; i++) {
  this[`userId${i}`] = ObjectId();
}

db.users.insertMany([
    {
        "_id": userId1,
        "lastName": "Doe",
        "firstName": "John",
        "email": "john.doe@example.com",
        "admin": true
    },
    {
        "_id": userId2,
        "lastName": "Smith",
        "firstName": "Jane",
        "email": "jane.smith@example.com",
        "admin": false
    },
    {
        "_id": userId3,
        "lastName": "Johnson",
        "firstName": "Robert",
        "email": "robert.johnson@example.com",
        "admin": true
    },
    {
        "_id": userId4,
        "lastName": "Brown",
        "firstName": "Emily",
        "email": "emily.brown@example.com",
        "admin": false
    },
    {
        "_id": userId5,
        "lastName": "Wilson",
        "firstName": "Olivia",
        "email": "olivia.wilson@example.com",
        "admin": false
    },
    {
        "_id": userId6,
        "lastName": "Jones",
        "firstName": "William",
        "email": "william.jones@example.com",
        "admin": true
    },
    {
        "_id": userId7,
        "lastName": "Taylor",
        "firstName": "Sophia",
        "email": "sophia.taylor@example.com",
        "admin": false
    },
    {
        "_id": userId8,
        "lastName": "Miller",
        "firstName": "Ethan",
        "email": "ethan.miller@example.com",
        "admin": true
    },
    {
        "_id": userId9,
        "lastName": "Anderson",
        "firstName": "Ava",
        "email": "ava.anderson@example.com",
        "admin": false
    },
    {
        "_id": userId10,
        "lastName": "Davis",
        "firstName": "Michael",
        "email": "michael.davis@example.com",
        "admin": true
    }
])

// creates 10 itemID variables
for (let i = 1; i <= 10; i++) {
  this[`itemId${i}`] = ObjectId();
}

db.items.insertMany([
    {
        "_id": itemId1,
        "name": "ProductA",
        "category": "Electronics",
        "high": 499.99,
        "low": 399.99
    },
    {
        "_id": itemId2,
        "name": "ProductB",
        "category": "Clothing",
        "high": 59.99,
        "low": 29.99
    },
    {
        "_id": itemId3,
        "name": "ProductC",
        "category": "Home Decor",
        "high": 79.99,
        "low": 49.99
    },
    {
        "_id": itemId4,
        "name": "ProductD",
        "category": "Books",
        "high": 29.99,
        "low": 19.99
    },
    {
        "_id": itemId5,
        "name": "ProductE",
        "category": "Toys",
        "high": 39.99,
        "low": 24.99
    },
    {
        "_id": itemId6,
        "name": "ProductF",
        "category": "Appliances",
        "high": 899.99,
        "low": 699.99
    },
    {
        "_id": itemId7,
        "name": "ProductG",
        "category": "Sports",
        "high": 129.99,
        "low": 79.99
    },
    {
        "_id": itemId8,
        "name": "ProductH",
        "category": "Beauty",
        "high": 49.99,
        "low": 34.99
    },
    {
        "_id": itemId9,
        "name": "ProductI",
        "category": "Furniture",
        "high": 349.99,
        "low": 249.99
    },
    {
        "_id": itemId10,
        "name": "ProductJ",
        "category": "Jewelry",
        "high": 199.99,
        "low": 149.99
    }
])

// creates 10 donationItemID variables
for (let i = 1; i <= 10; i++) {
  this[`donationItemId${i}`] = ObjectId();
}

db.donationItem.insertMany([
    {
        "_id": donationItemId1,
        "item": itemId1,
        "quantity": 10,
        "barcode": "ABC123",
        "value": {
            "price": 499.99,
            "evaluation": "High",
            "inRange": true
        }
    },
    {
        "_id": donationItemId2,
        "item": itemId2,
        "quantity": 5,
        "barcode": "XYZ456",
        "value": {
            "price": 29.99,
            "evaluation": "Low",
            "inRange": true
        }
    },
    {
        "_id": donationItemId3,
        "item": itemId3,
        "quantity": 8,
        "barcode": "123XYZ",
        "value": {
            "price": 9.99,
            "evaluation": "Other",
            "inRange": false
        }
    },
    {
        "_id": donationItemId4,
        "item": itemId4,
        "quantity": 15,
        "barcode": "789ABC",
        "value": {
            "price": 29.99,
            "evaluation": "High",
            "inRange": true
        }
    },
    {
        "_id": donationItemId5,
        "item": itemId5,
        "quantity": 3,
        "barcode": "456XYZ",
        "value": {
            "price": 24.99,
            "evaluation": "Low",
            "inRange": true
        }
    },
    {
        "_id": donationItemId6,
        "item": itemId6,
        "quantity": 12,
        "barcode": "XYZ123",
        "value": {
            "price": 599.99,
            "evaluation": "Other",
            "inRange": false
        }
    },
    {
        "_id": donationItemId7,
        "item": itemId7,
        "quantity": 6,
        "barcode": "789XYZ",
        "value": {
            "price": 129.99,
            "evaluation": "High",
            "inRange": true
        }
    },
    {
        "_id": donationItemId8,
        "item": itemId8,
        "quantity": 20,
        "barcode": "XYZ789",
        "value": {
            "price": 34.99,
            "evaluation": "Low",
            "inRange": true
        }
    },
    {
        "_id": donationItemId9,
        "item": itemId9,
        "quantity": 7,
        "barcode": "123ABC",
        "value": {
            "price": 599.99,
            "evaluation": "Other",
            "inRange": false
        }
    },
    {
        "_id": donationItemId10,
        "item": itemId10,
        "quantity": 4,
        "barcode": "ABC789",
        "value": {
            "price": 199.99,
            "evaluation": "High",
            "inRange": true
        }
    }
])

// creates 4 donationID variables
for (let i = 1; i <= 10; i++) {
  this[`donationId${i}`] = ObjectId();
}

db.donations.insertMany([
   {
        "user": userId1,
        "items": [itemId1],
        "entryDate": "2024-01-31",
        "donor": donorId1
    },
    {
        "user": userId1,
        "items": [itemId2, itemId4],
        "entryDate": "2024-02-01",
        "donor": donorId2
    },
    {
        "user": userId2,
        "items": [itemId4, itemId5, itemId6],
        "entryDate": "2024-02-02",
        "donor": donorId3
    },
    {
        "user": userId3,
        "items": [itemId7, itemId8, itemId9, itemId10],
        "entryDate": "2024-02-03",
        "donor": donorId4
    }
])